import { GeneralResponse } from "../../model/user";
import { ProductData } from "./../../model/product";
export const fakeProductResponse: GeneralResponse<ProductData[]> = {
  apiMsg: {
    rspCode: 1000,
    rspTitle: "Success",
    rspMsg: "Success",
  },
  data: [
    {
      id: 54,
      name: "car_b1",
      price: 3500,
      brand: "Ford",
      seatCount: 4,
      engineSize: 5000,
      yearOfManufacture: "2021",
      establishedDate: 20210131,
      lastModifyDate: 20210131,
      modifyBy: "root",
      description: "2021-01-31",
      productStatus: "2021-01-31",
      numOfDoor: null,
      fuelType: null,
      used: true,
      images: [
        {
          id: "1",
          filePath: "assets/product/car1.jpg",
          productId: "54",
        },
        {
          id: "3",
          filePath: "assets/product/car2.jpg",
          productId: "55",
        },
        {
          id: "3",
          filePath: "assets/product/car3.jpg",
          productId: "55",
        },
      ],
    },
    {
      id: 55,
      name: "car_c1",
      price: 15000,
      brand: "Honda",
      seatCount: 4,
      engineSize: 5000,
      yearOfManufacture: "2021",
      establishedDate: 20210131,
      lastModifyDate: 20210131,
      modifyBy: "root",
      description: "2021-01-31",
      productStatus: "2021-01-31",
      numOfDoor: null,
      fuelType: null,
      used: false,
      images: [
        {
          id: "3",
          filePath: "assets/product/car2.jpg",
          productId: "55",
        },
      ],
    },
    {
      id: 56,
      name: "car_a2",
      price: 12000,
      brand: "Toyota",
      seatCount: 4,
      engineSize: 5000,
      yearOfManufacture: "2021",
      establishedDate: 1661765193,
      lastModifyDate: 1661765193,
      modifyBy: "root",
      description: "1661765193",
      productStatus: "1661765193",
      numOfDoor: null,
      fuelType: null,
      used: true,
      images: [
        {
          id: "3",
          filePath: "assets/product/car3.jpg",
          productId: "55",
        },
      ],
    },
    {
      id: 57,
      name: "car_b2",
      price: 11000,
      brand: "Honda",
      seatCount: 4,
      engineSize: 5000,
      yearOfManufacture: "2021",
      establishedDate: 1661765193,
      lastModifyDate: 1661765193,
      modifyBy: "root",
      description: "1661765193",
      productStatus: "1661765193",
      numOfDoor: null,
      fuelType: null,
      used: false,
      images: [
        {
          id: "3",
          filePath: "assets/product/car1.jpg",
          productId: "55",
        },
      ],
    },
    {
      id: 58,
      name: "car_c2",
      price: 8000,
      brand: "Toyota",
      seatCount: 4,
      engineSize: 5000,
      yearOfManufacture: "2021",
      establishedDate: 1661765193,
      lastModifyDate: 1661765193,
      modifyBy: "root",
      description: "1661765193",
      productStatus: "1661765193",
      numOfDoor: null,
      fuelType: null,
      used: false,
      images: [
        {
          id: "3",
          filePath: "assets/product/car2.jpg",
          productId: "55",
        },
      ],
    },
    {
      id: 59,
      name: "car_a3",
      price: 9000,
      brand: "Honda",
      seatCount: 4,
      engineSize: 5000,
      yearOfManufacture: "2021",
      establishedDate: 1661765193,
      lastModifyDate: 1661765193,
      modifyBy: "root",
      description: "1661765193",
      productStatus: "1661765193",
      numOfDoor: null,
      fuelType: null,
      used: true,
      images: [
        {
          id: "3",
          filePath: "assets/product/car3.jpg",
          productId: "55",
        },
      ],
    },
    {
      id: 60,
      name: "car_b3",
      price: 5000,
      brand: "Ford",
      seatCount: 4,
      engineSize: 5000,
      yearOfManufacture: "2021",
      establishedDate: 1661765193,
      lastModifyDate: 1661765193,
      modifyBy: "root",
      description: "1661765193",
      productStatus: "1661765193",
      numOfDoor: null,
      fuelType: null,
      used: false,
      images: [
        {
          id: "3",
          filePath: "assets/product/car1.jpg",
          productId: "55",
        },
      ],
    },
  ],
};
